version: '2.1'
services:
  sa-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'

      # Schedule
      SCHEDULE_URL: '35.192.86.27'
      SCHEDULE_PORT: '5003'
      HORARIO_ENTRY: 'horario'
      AGENDADAS_ENTRY: 'agendadas'

    ports:
      - '5000:5000'
