version: '2.1'
services:
  sa-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'

      # Schedule
      SCHEDULE_URL: '146.148.107.218' #ipExternaFija MaquinaDenis
      SCHEDULE_PORT: '5003'
      HORARIO_ENTRY: 'horario'
      AGENDADAS_ENTRY: 'agendadas'

      #attatchment
      SCHEDULE_URL: '146.148.107.218' #ipExternaFija MaquinaDenis
      SCHEDULE_PORT: '3000'
      IMAGE_ENTRY: 'image'
      
    ports:
      - '5000:5000'
